Make epan_auto_reset_count configurable
tomlegkov/marine-python pull request #13
Opened 2020-03-31 05:16 UTC by assafrabin

2020-03-31 08:48 UTC, yehonatanz requested changes
Just please accept `epan_auto_reset_count` as an argument to `__init__`

2020-03-31 12:08 UTC, tomlegkov approved these changes

2020-03-31 12:08 UTC, tomlegkov commented on tests/marine/test_marine.py
> +    assert marine_instance.epan_auto_reset_count == SOME_VALUE
I think the convention is `expected == actual`, but I'll mark it as approved and leave it up to @yehonatanz to decide

2020-04-01 08:26 UTC, tomlegkov approved these changes
Tiny change and it looks good :)

2020-04-01 08:26 UTC, tomlegkov commented on marine/marine.py
> +    def __init__(self, lib_path, epan_auto_reset_count=None):
Add typing

2020-04-01 08:29 UTC, yehonatanz requested changes
I liked the `setter`/`getter`, didn't mean for you to remove them.

2020-04-01 08:29 UTC, yehonatanz commented on tests/fixtures/marine/marine_fixtures.py
> +def epan_auto_reset_count():
`-> int`

2020-04-01 08:29 UTC, yehonatanz commented on tests/fixtures/marine/marine_fixtures.py
> +def libmarine_path():
`-> str`

2020-04-01 08:29 UTC, yehonatanz commented on tests/fixtures/marine/marine_fixtures.py
> +def marine_instance(libmarine_path, epan_auto_reset_count) -> Marine:
typing

2020-04-19 10:59 UTC, yehonatanz requested changes
Tiny typing notes.
But also, I'd like to see back the `setter/getter`

2020-04-19 10:59 UTC, yehonatanz commented on tests/fixtures/marine/marine_fixtures.py
> +def marine_instance(libmarine_path: str, epan_auto_reset_count: int) -> object:
`-> Marine`

2020-04-19 10:59 UTC, yehonatanz commented on marine/marine.py
> +    def __init__(self, lib_path: str, epan_auto_reset_count: int = None):
`Optional[int]`

2020-04-19 12:02 UTC, yehonatanz approved these changes

2020-04-19 15:53 UTC, merged