Add flake8 and black to tox.ini
tomlegkov/marine-python pull request #14
Opened 2020-03-31 05:16 UTC by assafrabin

2020-03-31 08:50 UTC, yehonatanz requested changes

2020-03-31 08:50 UTC, yehonatanz commented on tox.ini
> +    pytest-black
I'd rather `flake8-black`, since that's linting, not testing.

2020-04-01 08:23 UTC, tomlegkov approved these changes

2020-04-01 08:25 UTC, yehonatanz approved these changes

2020-04-01 08:29 UTC, merged