Change/empty fields type
tomlegkov/marine-python pull request #33
Opened 2020-06-01 08:59 UTC by shaharyarn

2020-06-01 18:31 UTC, tomlegkov approved these changes

2020-06-02 05:16 UTC, yehonatanz requested changes
Just the tiniest most unimportant note and you can merge it

2020-06-02 05:16 UTC, yehonatanz commented on marine/marine.py
> +        return [value if len(value) > 0 else None for value in csv_parsed_output]
`value or None`

2020-07-12 07:48 UTC, shaharyarn reviewed
Change return typing to `Dict[str, Optional[str]]`

2020-07-22 18:45 UTC, tomlegkov approved these changes

2020-07-22 19:35 UTC, yehonatanz approved these changes

2020-08-30 14:32 UTC, merged