Add custom exceptions to add_or_get_filter
tomlegkov/marine-python pull request #38
Opened 2020-07-14 13:33 UTC by domerd

Closes issue #7.
Ran Black.

2020-07-14 14:51 UTC, tomlegkov requested changes

2020-07-14 14:51 UTC, tomlegkov commented on marine/marine.py
> +                if filter_id == -1:
I think we should continue the trend of importing consts from the `.so` file, and also import these consts.

2020-07-14 14:51 UTC, tomlegkov commented on marine/marine.py
> +from marine.exceptions import (
Relative import

2020-07-14 14:54 UTC, yehonatanz requested changes

2020-07-14 14:54 UTC, yehonatanz commented on marine/marine.py
> +                raise ValueError(err)
Shouldn't we use a custom exception here as well?

2020-07-15 07:56 UTC, yehonatanz requested changes

2020-07-15 07:56 UTC, yehonatanz commented on marine/marine.py
> +                    raise BadBPFException(err)
Looks great, juts change the casing here after you change it in the C code

2020-07-15 18:42 UTC, yehonatanz approved these changes

2020-07-16 17:43 UTC, tomlegkov approved these changes

2020-07-19 09:10 UTC, shaharyarn approved these changes

2020-07-23 17:27 UTC, merged