Feature/test action
tomlegkov/marine-python pull request #48
Opened 2020-10-08 13:46 UTC by domerd

2020-10-08 15:00 UTC, yehonatanz requested changes

2020-10-08 15:00 UTC, yehonatanz commented on .github/workflows/test.yml
> +    branches: [ master ]
Why not always? I'd like the CI to run on my branch even before I open a PR

2020-10-08 15:00 UTC, yehonatanz commented on Dockerfile
> +RUN python3.8 -m pip install tox
How does this image have python3.8?
Shouldn't you `apt install` it just before this `RUN`?

2020-10-08 15:00 UTC, yehonatanz commented on .github/workflows/test.yml
> +      run: docker run -i --rm -e LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu -v $(pwd)/:/marine-python marine-python
Is the `-e LD_LIBRARY_PATH=...` still needed after you properly install marine in `marine-core`?

2020-10-08 15:00 UTC, yehonatanz commented on .github/workflows/test.yml
> +      run: docker run -i --rm -e LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu -v $(pwd)/:/marine-python marine-python
No need for `/` after `$(pwd)`

2020-10-08 15:00 UTC, yehonatanz commented on .dockerignore
> +venv
Add .venv please :)

2021-01-10 09:56 UTC, domerd commented on Dockerfile
> +RUN python3.8 -m pip install tox
` libglib2.0-dev` installs python3.8 on `marine-core`, therefore it is pre-built.

2021-01-10 10:16 UTC, yehonatanz approved these changes

2021-01-10 10:18 UTC, merged