Add ws_data_dir to wheel
tomlegkov/marine-python pull request #57
Opened 2021-03-02 16:04 UTC by danielg55

2021-03-02 17:02 UTC, yehonatanz requested changes
I'd like to see a test verifying your changes if that's not too expensive, and of course I assume you have manually tried that and it works

2021-03-02 17:02 UTC, yehonatanz commented on Dockerfile
> +    rsync -r --exclude "lib*.so*" /build/run/* marine/.ws_data_dir && \
Be consistent with your usage of `rsync` and `cp` please

2021-03-02 17:04 UTC, yehonatanz commented
Also I think you should modify our `setup.py` and perhaps prefer having a single `.ws` dir with `libs` and `data` inside

2021-03-07 15:08 UTC, danielg55 commented
I can't think of a way to test this change, since it should only affect plugins.

2021-03-07 15:17 UTC, yehonatanz approved these changes

2021-03-07 16:00 UTC, merged